AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  MasterAccountID: 
    Type: String
    Description: Enter the account ID of the master account.
Resources:
  LambdaExecutionRoleForConfig:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
              AWS:
                - !Sub "arn:aws:iam::${MasterAccountID}:role/LambdaExecutionRoleForConfig"
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
      - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      - "arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole"
      RoleName: LambdaExecutionRoleForConfig
  AutomationLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
              AWS:
                - !Sub "arn:aws:iam::${MasterAccountID}:role/AutomationLambdaRole"
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      RoleName: AutomationLambdaRole
  AutomationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
              - ssm.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
      - "arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole"
      RoleName: AutomationRole
