version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-eventbridge-fanout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7v24nrjutgyu"
s3_prefix = "sam-eventbridge-fanout"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

